### ISSUE TITLE
关于gif图的报错

### ISSUE THREAD

**Issue by gaoyong06** [xinyu1205/Tag2Text#10]
用一个gif图在huggingface上面测试，一切正常. 当时使用inference.py脚本执行的时候，会出现错误. 错误信息如下：

```
D:\work\Tag2Text>python D:/work/Tag2Text/inference.py --image C:/Users/gaoyo/Desktop/9346691egw1fb9c0fxebug20zk0jg4bl.gif
Traceback (most recent call last):
  File "D:/work/Tag2Text/inference.py", line 92, in <module>
    image = transform(raw_image).unsqueeze(0).to(device)
  File "C:\Users\gaoyo\.conda\envs\base\lib\site-packages\torchvision\transforms\transforms.py", line 95, in __call__
    img = t(img)
  File "C:\Users\gaoyo\.conda\envs\base\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\gaoyo\.conda\envs\base\lib\site-packages\torchvision\transforms\transforms.py", line 277, in forward
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "C:\Users\gaoyo\.conda\envs\base\lib\site-packages\torchvision\transforms\functional.py", line 363, in normalize
    return F_t.normalize(tensor, mean=mean, std=std, inplace=inplace)
  File "C:\Users\gaoyo\.conda\envs\base\lib\site-packages\torchvision\transforms\_functional_tensor.py", line 928, in normalize
    return tensor.sub_(mean).div_(std)
RuntimeError: output with shape [1, 384, 384] doesn't match the broadcast shape [3, 384, 384]
```
测试使用的git图：
![9346691egw1fb9c0fxebug20zk0jg4bl](https://github.com/xinyu1205/Tag2Text/assets/1861256/2b058adb-ae1d-47d2-9b56-8cafdd5b52ad)

huggingface上面执行正常的截图：
![20230606110204](https://github.com/xinyu1205/Tag2Text/assets/1861256/ed42447f-abff-48e7-9d70-d1ce7a46b1c8)

期望是：inference.py 里面也可以工作正常

@xinyu1205  麻烦看一下，是哪里出问题了，多谢.

**Comment by xinyu1205** [comment]
Hi, 感谢您的关注以及非常有价值的issues。该问题应该是在读取图像时，需要将git图像转为RGB三通道的格式。
具体解决办法应该是inference.py里的#90行代码
    raw_image = Image.open(args.image).resize(
        (args.image_size, args.image_size))
改为
    raw_image = Image.open(args.image).convert("RGB").resize(
        (args.image_size, args.image_size))
我自己已经通过了测试，后面会在仓库中修复该BUG。祝好~

**Comment by gaoyong06** [comment]
可以了！测试通过！感谢感谢
